# Generated by Django 2.2.16 on 2022-11-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221031_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='test',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
