# Generated by Django 2.2.16 on 2022-11-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follow_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='test',
        ),
    ]
